baseURL = 'https://stantonbydalehistory.github.io/'
languageCode = 'en-us'
title = "Stanton-by-Dale - A Village's History"

[params]
googleAnalytics = "G-P1Y8NME5YH"

[taxonomies]
street = "streets"
theme = "themes"
institution_type = "institution_types"
resident_role = "resident_roles"
