baseURL = 'https://stantonbydalehistory.github.io/'
languageCode = 'en-us'
title = "Stanton-by-Dale - A Village's History"

[taxonomies]
street = "streets"
theme = "themes"
business_type = "business_types"
resident_role = "resident_roles"
